language: ruby
rvm:
- 2.4
dist: trusty
sudo: false
cache:
  directories:
  - "$HOME/.berkshelf"
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
install:
- eval "$(chef shell-init bash)"
before_script:
- chef --version
script: $TEST
env:
  matrix:
  - TEST='delivery local verify'
  - TEST='kitchen test default-ubuntu-1404'
  - TEST='kitchen test default-ubuntu-1604'
  - TEST='kitchen test default-centos-7'
  - TEST='kitchen test attributes-ubuntu-1404'
  - TEST='kitchen test attributes-ubuntu-1604'
  - TEST='kitchen test attributes-centos-7'
  - TEST='kitchen test upstart-ubuntu-1404'
  - TEST='kitchen test systemd-ubuntu-1604'
  - TEST='kitchen test systemd-centos-7'
notifications:
  slack:
    secure: Bh2Lb596AhPXzFOviP+pVhQaZxXN1ry3swomyXELNvKRbQPcdHNn4slgZXhWplRo1XQUsSGSBmrdwoNAWpvNGQnLTyz8hAI1wmUnc0KEF/4RGaKbzsuuhvctFbiSaO1u/Y9yZ1hT9RW6fbM4TepJ5+DoI0q9PxDRuXPnGd2RnWg=
